server:
  port: 8764
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: 120.79.218.226
    port: 5672
    username: admin
    password: admin
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability : 1
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
